print ("###############################")
print ("#                             #")
print ("#   Muhammad Aufa Fitrianda   #")
print ("#        2310817210013        #")
print ("#                             #")
print ("###############################")